export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';

export const TOGGLE_CAUGHT = 'TOGGLE_CAUGHT';
export const REQUEST_POKEMON_LIST = 'REQUEST_POKEMON_LIST';
export const RECEIVE_POKEMON_LIST = 'RECEIVE_POKEMON_LIST';

export const REQUEST_POKEMON_DETAIL = 'REQUEST_POKEMON_DETAIL';
export const RECEIVE_POKEMON_DETAIL = 'RECEIVE_POKEMON_DETAIL';
